# -*- coding: utf-8 -*-
"""WorldCup_2022_data_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N8WR6jtPeTqzbSfx2zYsqRnatQpnHi3m
"""

pip install bs4

pip install lxml

pip install requests

pip install pandas

import pandas as pd
from bs4 import BeautifulSoup
import requests


def scrape_matches(year):

  web = f'https://en.wikipedia.org/wiki/{year}_FIFA_World_Cup'

  response = requests.get(web)
  content = response.text
  soup = BeautifulSoup(content, 'lxml')

  games = soup.find_all('div', class_='footballbox')

  teamA = []
  teamB = []
  score = []

  for g in games:
    teamA.append(g.find('th', class_='fhome').get_text())
    teamB.append(g.find('th', class_='faway').get_text())
    score.append(g.find('th', class_='fscore').get_text())

  world_cup_dict = {'teamA':teamA, 'score':score, 'teamB':teamB}
  world_cup_df = pd.DataFrame(world_cup_dict)
  world_cup_df['year'] = year

  return world_cup_df

considered_years = [2014, 2018]
for y in considered_years:
  print(scrape_matches(y))

full_data_set = [scrape_matches(y) for y in considered_years]

full_data_frame = pd.concat(full_data_set, ignore_index=True)
full_data_frame.to_csv("worldcup_data_14_to_18.csv", index=False)